export const chatRoomNames = [
  "General Talk",
  "Code & Coffee",
  "Meme Machine",
  "Late Night Rants",
  "Study Squad",
  "Tech Trends",
  "Crypto Cave",
  "Startup Zone",
  "Gaming Lobby",
  "Design Den",
  "Random Banter",
  "Quiet Corner",
  "AI Alley",
  "Frontend Fanatics",
  "Backend Bunker",
  "The Debugging Dojo",
  "UX/UI Underground",
  "Idea Exchange",
  "Remote Rants",
  "Daily Standup",
];
export const colors = {
  blurple: "#5865F2",
  fuchsia: "#EB459E",
  green: "#57F287",
  yellow: "#FEE75C",
  red: "#ED4245",
  white: "#FFFFFF",
  black: "#000000",
  grey: "#2C2F33",
  darkGrey: "#23272A",
  lightGrey: "#99AAB5",
  text: "#DCDDDE",
  background: "#36393F",
};
